services:
  - type: web
    name: globalbridge-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

